theme: jekyll-theme-cayman
title: The Social Network Analysis of US Academic Anthropology 2022
description: 2022 KU Leuven Data Visualization Group Assignment Group 8
              Huangjin Zhu, Yang Zhao, Yawen Zhao, Junyu An, Xiaoyong Zhou


